variables:
  IMAGE_NAME : noviantoro/angular-webapp

stages:
  - build

build:docker:
  stage: build
  image: docker:stable
  services:
    - name: docker:18.09-dind
      alias: dockerd
  variables:
    DOCKER_HOST: tcp://dockerd:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME





